# Generated by Django 6.0.5 on 2026-07-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='autos',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='anio',
        ),
        migrations.AlterModelTable(
            name='auto',
            table='autos_autos',
        ),
    ]
