# Generated by Django 6.0.5 on 2026-07-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_rename_autos_auto_rename_año_auto_anio_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auto',
            table='autos_auto',
        ),
    ]
