# Generated by Django 6.0.5 on 2026-07-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
        ('fabrica', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('ubicacion_bodega', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(default='Sí', max_length=2)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.fabrica')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'stock_stock',
            },
        ),
    ]
