# Generated by Django 6.0.5 on 2026-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='estatus',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
