# Generated by Django 6.0.5 on 2026-07-07 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_alter_auto_table'),
        ('fabrica', '0002_alter_fabrica_table'),
        ('proveedor', '0002_alter_proveedor_table'),
        ('stock', '0002_alter_stock_disponibilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='modelo_auto',
            new_name='ubicacion_bodega',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='stock',
            name='auto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autos.auto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='fabrica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fabrica.fabrica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
            preserve_default=False,
        ),
    ]
