# Generated by Django 6.0.5 on 2026-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_modelo_auto_stock_ubicacion_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='disponibilidad',
            field=models.CharField(default='Sí', max_length=2),
        ),
    ]
