# Generated by Django 6.0.5 on 2026-07-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_auto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('sucursal', models.CharField(max_length=100)),
                ('fecha_venta', models.DateField()),
                ('vendedor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ventas_venta',
            },
        ),
    ]
