# Generated by Django 6.0.5 on 2026-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estatus',
            field=models.CharField(default='Completada', max_length=20),
        ),
    ]
