# Generated by Django 6.0.5 on 2026-07-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_alter_auto_table'),
        ('clientes', '0003_alter_cliente_table'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='modelo_auto',
        ),
        migrations.AddField(
            model_name='venta',
            name='auto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autos.auto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
