# Generated by Django 6.0.5 on 2026-07-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor_proveedor',
        ),
    ]
