# Generated by Django 6.0.5 on 2026-07-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='empleados',
            new_name='empleado',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados_empleados',
        ),
    ]
