# Generated by Django 6.0.5 on 2026-07-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_prueba', models.DateField()),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('empleado_encargado', models.CharField(max_length=100)),
                ('mecanico_asignado', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'pruebas_pruebas',
            },
        ),
    ]
