# Generated by Django 6.0.5 on 2026-07-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
        ('empleados', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_prueba', models.DateField()),
                ('estatus', models.CharField(default='Programada', max_length=20)),
                ('autos', models.ManyToManyField(related_name='pruebas', to='autos.auto')),
                ('empleado_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_encargadas', to='empleados.empleado')),
                ('mecanico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_mecanico', to='empleados.empleado')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
            ],
        ),
    ]
