# Generated by Django 6.0.5 on 2026-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='mecanico_asignado',
            field=models.CharField(max_length=100),
        ),
    ]
