# Generated by Django 6.0.5 on 2026-07-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('pruebas', '0001_initial'),
        ('taller', '0002_remove_taller_auto_remove_taller_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='mecanico_asignado',
        ),
        migrations.AddField(
            model_name='prueba',
            name='taller_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas', to='taller.taller'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='empleado_encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
