# Generated by Django 6.0.5 on 2026-06-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad_produccion', models.IntegerField()),
                ('fecha_fundacion', models.DateField()),
                ('procesos_activos', models.CharField(max_length=200)),
            ],
        ),
    ]
