# Generated by Django 6.0.5 on 2026-07-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fabrica',
            table='fabricas_fabricas',
        ),
    ]
