# Generated by Django 6.0.5 on 2026-07-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_clientes',
        ),
    ]
