# Generated by Django 6.0.5 on 2026-07-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_apellido_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_cliente',
        ),
    ]
