# Generated by Django 6.0.5 on 2026-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_reparacion', models.CharField(max_length=100)),
                ('nombre_auto', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=200)),
                ('mecanico', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='En proceso', max_length=20)),
            ],
            options={
                'db_table': 'taller_taller',
            },
        ),
    ]
