# Generated by Django 6.0.5 on 2026-07-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('descripcion_problema', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'taller_taller',
            },
        ),
    ]
