# Generated by Django 6.0.5 on 2026-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='descripcion_problema',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_entrada',
        ),
        migrations.AddField(
            model_name='taller',
            name='mecanico',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='orden_reparacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='servicio',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='En proceso', max_length=20),
        ),
    ]
