# Generated by Django 6.0.5 on 2026-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='mecanico',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='taller',
            name='estatus',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='taller',
            name='nombre',
            field=models.CharField(default='Taller Central', max_length=100),
        ),
        migrations.AddField(
            model_name='taller',
            name='orden_reparacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='servicio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='estado',
            field=models.CharField(default='En proceso', max_length=20),
        ),
    ]
